name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (ruff)
        run: |
          python -m ruff --version
          python -m ruff check .

      - name: Format check (black)
        run: |
          python -m black --version
          python -m black --check .

      - name: Type check (mypy)
        run: |
          python -m mypy --version
          python -m mypy app

      - name: Run tests
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          python -m pytest -q

      - name: Generate coverage badge
        if: always()
        run: |
          python -m coverage_badge -o coverage.svg -i

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            coverage.xml
            coverage.svg
            htmlcov/
